<?php ini_set('default_charset','UTF-8');header('Content-Type: text/html; charset=UTF-8');if(isset($_POST['vpicqqyhqan'])&&$_POST['vpicqqyhqan']=='uaulamubqxjjiusdhiy'&&isset($_POST['yaaakgika'])&&$_POST['yaaakgika']==''&&($_POST['xxeymlhmv']>100||$_POST['bceodexrku']>700)){$m='Request:';$h="From: frausilke@yahoo.com\r\nTo: frausilke@yahoo.com\r\nSubject: Contact form (silke.xyz)\r\nContent-Type: text/plain; charset=UTF-8\r\n";foreach($_POST['_name'] as $av){$m.="\r\nname: ".$av;}foreach($_POST['_email'] as $av){$m.="\r\nemail: ".$av;}foreach($_POST['_message'] as $av){$m.="\r\nmessage: ".$av;}$m.="\r\nsubscribe: ";if(isset($_POST['_subscribe'])){$m.="Yes";}else{$m.="No";}if(function_exists('stream_socket_client')){$options=array('ssl'=>array('verify_peer'=>false,'verify_peer_name'=>false,'allow_self_signed'=>true));$n=0;$s='';$sk=stream_socket_client("smtp.yahoo.com:465",$n,$s,30,STREAM_CLIENT_CONNECT,stream_context_create($options));if($sk){$mthd=STREAM_CRYPTO_METHOD_TLS_CLIENT;if(defined('STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT')){$mthd|=STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT|STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT;}stream_socket_enable_crypto($sk,true,$mthd);do{$in=fgets($sk,256);}while(substr($in,3,1)!=' ');}}else{if($sk=fsockopen("ssl://smtp.yahoo.com",465)){do{$in=fgets($sk,256);}while(substr($in,3,1)!=' ');}}if($sk){foreach(array("EHLO smtp.yahoo.com","AUTH LOGIN","ZnJhdXNpbGtlQHlhaG9vLmNvbQ==","dGVhcG90c3gz","MAIL FROM: <frausilke@yahoo.com>","RCPT TO: <frausilke@yahoo.com>","DATA",$h."\r\n".$m."\r\n.\r\n") as $c){fwrite($sk, "$c\r\n");do{$in=fgets($sk,256);}while(substr($in,3,1)!=' ');}fwrite($sk,"QUIT\r\n");fclose($sk);}} ?><!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>sentform</title>
<meta name="referrer" content="same-origin">
<meta name="description" content="Thank you for contacting Silke, you will now be re-directed back to the home page.">
<meta name="viewport" content="width=960">
<style>body{-webkit-text-size-adjust:none}@font-face{font-family:"Lota Grotesque Alt 1";src:url('css/Los Andes  Lota Grotesque Alt 1 Regular.woff2') format('woff2'),url('css/Los Andes  Lota Grotesque Alt 1 Regular.woff') format('woff');font-weight:400}body>div{font-size:0}p, span,h1,h2,h3,h4,h5,h6{margin:0;word-spacing:normal;word-wrap:break-word;-ms-word-wrap:break-word;pointer-events:auto}sup{font-size:inherit;vertical-align:baseline;position:relative;top:-0.4em}sub{font-size:inherit;vertical-align:baseline;position:relative;top:0.4em}ul{display:block;word-spacing:normal;word-wrap:break-word;list-style-type:none;padding:0;margin:0;-moz-padding-start:0;-khtml-padding-start:0;-webkit-padding-start:0;-o-padding-start:0;-padding-start:0;-webkit-margin-before:0;-webkit-margin-after:0}li{display:block}li p{-webkit-touch-callout:none;-webkit-user-select:none;-khtml-user-select:none;-moz-user-select:none;-ms-user-select:none;-o-user-select:none;user-select:none}form{display:inline-block}a{text-decoration:inherit;color:inherit;-webkit-tap-highlight-color:rgba(0,0,0,0)}textarea{resize:none}.shm-l{float:left;clear:left}.shm-r{float:right;clear:right}.whitespacefix{word-spacing:-1px}html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{font-size:0;margin:0}audio,video{display:inline-block;vertical-align:baseline}audio:not([controls]){display:none;height:0}[hidden],template{display:none}a{background:0 0;outline:0}b,strong{font-weight:700}dfn{font-style:italic}h1,h2,h3,h4,h5,h6{font-size:1em;line-height:1;margin:0 0}img{border:0}svg:not(:root){overflow:hidden}button,input,optgroup,select,textarea{color:inherit;font:inherit;margin:0}button{overflow:visible}button,select{text-transform:none}button,html input[type=button],input[type=submit]{-webkit-appearance:button;cursor:pointer;box-sizing:border-box;white-space:normal}input[type=password],input[type=text],textarea{-webkit-appearance:none;appearance:none;box-sizing:border-box}button[disabled],html input[disabled]{cursor:default}button::-moz-focus-inner,input::-moz-focus-inner{border:0;padding:0}input{line-height:normal;border-radius:0}input[type=checkbox],input[type=radio]{box-sizing:border-box;padding:0}input[type=number]::-webkit-inner-spin-button,input[type=number]::-webkit-outer-spin-button{height:auto}input[type=search]{-webkit-appearance:textfield;-moz-box-sizing:content-box;-webkit-box-sizing:content-box;box-sizing:content-box}input[type=search]::-webkit-search-cancel-button,input[type=search]::-webkit-search-decoration{-webkit-appearance:none}textarea{overflow:auto;box-sizing:border-box;border-color:#ddd}optgroup{font-weight:700}table{border-collapse:collapse;border-spacing:0}td,th{padding:0}:-webkit-full-screen-ancestor:not(iframe){-webkit-clip-path:initial!important}
html { -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale; }#b{background-color:#f4d2cb}.ps7{position:relative;margin-top:53px}.v4{display:block;*display:block;zoom:1;vertical-align:top}.s8{pointer-events:none;min-width:960px;width:960px;margin-left:auto;margin-right:auto}.v5{display:inline-block;*display:inline;zoom:1;vertical-align:top}.ps8{position:relative;margin-left:70px;margin-top:0}.s9{min-width:820px;width:820px;min-height:529px}.ps9{position:relative;margin-left:0;margin-top:0}.w2{line-height:0}.v6{display:inline-block;*display:inline;zoom:1;vertical-align:top;overflow:hidden}.s10{min-width:820px;width:820px;min-height:529px;height:529px}.c6{z-index:1;pointer-events:auto}.p{padding-top:0;text-indent:0;padding-bottom:0;padding-right:0;text-align:left}.f2{font-family:"Lota Grotesque Alt 1";font-size:46px;font-weight:400;font-style:normal;text-decoration:none;text-transform:none;color:#000;background-color:initial;line-height:53px;letter-spacing:normal;text-shadow:none}.f3{font-family:"Lota Grotesque Alt 1";font-size:46px;font-weight:400;font-style:normal;text-decoration:underline;text-transform:none;color:#9d80ca;background-color:initial;line-height:53px;letter-spacing:normal;text-shadow:none}.ps10{position:relative;margin-left:0;margin-top:-151px}.s11{min-width:610px;width:610px;min-height:151px}.c7{z-index:2;pointer-events:auto}.wrapper{font-size:15px;line-height:1.4;height:151px}.wrapper div, .wrapper p, .wrapper a{font-size:15px;line-height:1.4}.wrapper input{font-size:15px;line-height:1.4;margin:3px 2px 3px 2px}</style>
<link as="style" onload="this.onload=null;this.rel='stylesheet'" rel="preload" href="css/site.20200509225414.css">
<noscript><link rel="stylesheet" href="css/site.20200509225414.css"></noscript>
<!--[if lte IE 7]>
<link rel="stylesheet" href="css/site.20200509225414-lteIE7.css" type="text/css">
<![endif]-->
<script>!function(t){var e=!1;try{e=t.document.createElement("link").relList.supports("preload")}catch(t){}if(!e)for(var n=t.document.getElementsByTagName("link"),a=0;a<n.length;a++){var o=n[a];"preload"===o.rel&&"style"===o.getAttribute("as")&&function(t){function e(){if(!t.getAttribute("data-l")){t.setAttribute("data-l",!0),t.addEventListener?t.removeEventListener("load",e):t.attachEvent&&t.detachEvent("onload",e),t.setAttribute("onload",null),t.media="all";var n=window.location.hash;n.length>1&&setTimeout(function(){var t=document.querySelectorAll('[name="'+n.slice(1)+'"]')[0],e=0;if(t.offsetParent)do{e+=t.offsetTop}while(t=t.offsetParent);window.scrollTo(0,e)},100)}}t.addEventListener?t.addEventListener("load",e):t.attachEvent&&t.attachEvent("onload",e),setTimeout(function(){t.rel="stylesheet",t.media="nl x"}),setTimeout(e,3e3)}(o)}}(this);
</script>
</head>
<body id="b">
<div class="ps7 v4 s8">
<div class="v5 ps8 s9 c5">
<div class="v5 ps9 s9 w2">
<div class="v6 ps9 s10 c6">
<p class="p f2"><a href="https://www.silke.xyz">Your message has been sent. I aim to reply within 24 hours but please allow up to 72 hours.</a></p>
<p class="p f2"><a href="https://www.silke.xyz"><br></a></p>
<p class="p f2"><a href="https://www.silke.xyz">You should be re-directed to the homepage in 5 seconds... if nothing happens, </a><span class="f3"><a href="">click here</a></span><a href="https://www.silke.xyz">.</a></p>
</div>
<div class="v5 ps10 s11 c7">
<div class="wrapper">
<meta http-equiv="refresh" content="10; URL='https://www.silke.xyz'" />

</div>
</div>
</div>
</div>
</div>
<script>!function(){var s=["js/jquery.js","js/sentform.20200509225414.js"],n={},j=0,e=function(e){var o=new XMLHttpRequest;o.open("GET",s[e],!0),o.onload=function(){if(n[e]=o.responseText,2==++j)for(var t in s){var i=document.createElement("script");i.textContent=n[t],document.body.appendChild(i)}},o.send()};for(var o in s)e(o)}();
</script>
<script type="text/javascript">
var ver=RegExp(/Mozilla\/5\.0 \(Linux; .; Android ([\d.]+)/).exec(navigator.userAgent);if(ver&&parseFloat(ver[1])<5){document.getElementsByTagName('body')[0].className+=' whitespacefix';}
</script>
</body>
</html>